# Generated by Django 3.1.3 on 2020-11-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_remove_productcategory_product_category'),
        ('Product', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='Category.ProductCategory', verbose_name='دسته بندی ها'),
        ),
    ]
