# Generated by Django 3.1.3 on 2020-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0001_initial'),
        ('Product', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, to='Brand.Product_Brand', verbose_name='برند'),
        ),
    ]
