# Generated by Django 3.1.3 on 2020-11-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_product_slug'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='Product.Product'),
        ),
    ]
