# Generated by Django 3.1.3 on 2020-11-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_productcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='product_category',
        ),
    ]
