# Generated by Django 3.1.3 on 2020-11-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
