# Generated by Django 3.1.3 on 2020-11-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site_setting',
            options={'verbose_name': 'تنظیمات', 'verbose_name_plural': 'گروه تنظیمات'},
        ),
    ]
