# Generated by Django 3.1.3 on 2020-11-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='پرداخت شده'),
        ),
    ]
